# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\000039r2s3u\tmp\build\80754af9\rsync-recipes\reportlab-3.5.23-c_compiler_vs2017-python_3.7-on-winbuilder, last modified Thu Jun  6 14:34:56 2019
# ------------------------------------------------

package:
    name: reportlab
    version: 3.5.23
source:
    fn: reportlab-3.5.23.tar.gz
    sha256: 6c81ee26753fa09062d8404f6340eefb02849608b619e3843e0d17a7cda8798f
    url: https://pypi.io/packages/source/r/reportlab/reportlab-3.5.23.tar.gz
build:
    number: '0'
    string: py37h3e46f66_0
requirements:
    build:
        - vs2017_win-64 19.15.26726 hb4ce483_4
    host:
        - ca-certificates 2019.5.15 0
        - certifi 2019.3.9 py37_0
        - freetype 2.9.1 ha9979f8_1
        - jpeg 9b hb83a4c4_2
        - libpng 1.6.37 h2a8f88b_0
        - libtiff 4.0.10 hb898794_2
        - olefile 0.46 py37_0
        - openssl 1.1.1c he774522_1
        - pillow 6.0.0 py37hdc69c19_0
        - python 3.7.3 h8c8aaf0_1
        - setuptools 41.0.1 py37_0
        - sqlite 3.28.0 he774522_0
        - tk 8.6.8 hfa6e2cd_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_4
        - wincertstore 0.2 py37_0
        - xz 5.2.4 h2fa13f4_4
        - zlib 1.2.11 h62dcd97_3
        - zstd 1.3.7 h508b16e_0
    run:
        - freetype >=2.9.1,<3.0a0
        - pillow >=2.4.0
        - python >=3.7,<3.8.0a0
        - vc >=14.1,<15.0a0
test:
    imports:
        - reportlab
        - reportlab.graphics
        - reportlab.graphics.barcode
        - reportlab.graphics.charts
        - reportlab.graphics.samples
        - reportlab.graphics.widgets
        - reportlab.lib
        - reportlab.pdfbase
        - reportlab.pdfgen
        - reportlab.platypus
about:
    doc_url: http://www.reportlab.com/documentation/
    home: http://www.reportlab.com/opensource/
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE.txt
    summary: Open-source engine for creating complex, data-driven PDF documents and
        custom vector graphics
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - mcs07
